#
# A corrected and secure docker-compose.yml for a PUBLIC Geth/Prysm Ethereum Mainnet Node
#
# !!! --- SECURITY WARNING --- !!!
# This configuration exposes your node's APIs to the public internet.
# YOU ARE RESPONSIBLE for securing the host machine with a firewall.
#
# To use this file:
# 1. Ensure you have a 'jwt.hex' file in this directory.
# 2. **CRITICAL: Replace '0xYOUR_FEE_RECIPIENT_ADDRESS' with your actual Ethereum address.**
# 3. Stop your existing containers: `docker-compose down`
# 4. Use this new file and restart: `docker-compose up -d`
#
version: "3.9"

volumes:
  geth-data:
  prysm-data:

services:
  #
  # Geth (Execution Layer Client)
  #
  geth:
    container_name: geth
    image: ethereum/client-go:stable
    restart: unless-stopped
    ports:
      # P2P port for execution layer peering.
      - "30303:30303/tcp"
      - "30303:30303/udp"
      # Public RPC ports (secure your host with a firewall).
      - "8545:8545/tcp"  # Public HTTP JSON-RPC
      - "8546:8546/tcp"  # Public WebSocket JSON-RPC
    volumes:
      - geth-data:/data
      - ./jwt.hex:/etc/ethereum/jwt.hex
    command:
      - --mainnet
      # --- Engine API Settings (CRITICAL for CL communication, NOT public) ---
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      # --- FIX: Explicitly allow the 'geth' and 'localhost' hostnames ---
      - --authrpc.vhosts=geth,localhost
      - --authrpc.jwtsecret=/etc/ethereum/jwt.hex
      # --- Public HTTP RPC Settings ---
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts="*"
      - --http.api=eth,net,web3
      # --- Public WebSocket RPC Settings ---
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.origins="*"
      - --ws.api=eth,net,web3
      # --- Other Recommended Settings ---
      - --datadir=/data
      - --cache=4096
      - --metrics
      - --metrics.addr=0.0.0.0

  #
  # Prysm (Consensus Layer Client - Beacon Node)
  #
  prysm:
    container_name: prysm
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    restart: unless-stopped
    depends_on:
      - geth
    ports:
      # P2P ports for consensus layer peering.
      - "13000:13000/tcp"
      - "12000:12000/udp"
      # Public Beacon API port (secure your host with a firewall).
      - "3500:3500/tcp"
      # Optional Public Monitoring Port.
      - "8080:8080/tcp"
    volumes:
      - prysm-data:/data
      - ./jwt.hex:/etc/ethereum/jwt.hex
    command:
      - --mainnet
      # --- Engine API Connection Settings ---
      - --execution-endpoint=http://geth:8551
      - --jwt-secret=/etc/ethereum/jwt.hex
      # --- Fee Recipient Settings (CRITICAL) ---
      # ** REPLACE THIS WITH YOUR OWN ETHEREUM ADDRESS **
      - --suggested-fee-recipient=0x764a3D06E365e73085Bb489Da970E438F3C01c75
      # --- Checkpoint Sync (Speeds up initial sync dramatically) ---
      - --checkpoint-sync-url=https://beaconstate.ethstaker.cc
      - --genesis-beacon-api-url=https://beaconstate.ethstaker.cc
      # --- Other Recommended Settings ---
      - --datadir=/data
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --grpc-gateway-port=3500
      - --monitoring-host=0.0.0.0
      - --monitoring-port=8080
      - --accept-terms-of-use
