version: "3.9"

volumes:
  geth-data:
  prysm-data:

services:
  geth:
    container_name: geth
    image: ethereum/client-go:v1.15.11
    restart: unless-stopped
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
    volumes:
      - geth-data:/data
      - ./jwt.hex:/etc/ethereum/jwt.hex
    command:
      - --mainnet
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=localhost,geth,prysm
      - --authrpc.jwtsecret=/etc/ethereum/jwt.hex
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts=localhost,127.0.0.1
      - --http.api=eth,net,web3
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.origins=localhost,127.0.0.1
      - --ws.api=eth,net,web3
      - --datadir=/data
      - --db.engine=pebble
      - --cache=8192
      - --gcmode=archive
      - --syncmode=snap
      - --txlookuplimit=0
      - --metrics
      - --metrics.addr=0.0.0.0
      - --snapshot.verification=all
      - --override.terminaltotaldifficulty=58750000000000000000000

  prysm:
    container_name: prysm
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v5.0.4
    restart: unless-stopped
    depends_on:
      geth:
        condition: service_started
    ports:
      - "13000:13000/tcp"
      - "12000:12000/udp"
      - "3500:3500/tcp"
      - "8080:8080/tcp"
    volumes:
      - prysm-data:/data
      - ./jwt.hex:/etc/ethereum/jwt.hex
    command:
      - --mainnet
      - --accept-terms-of-use
      - --execution-endpoint=http://geth:8551
      - --jwt-secret=/etc/ethereum/jwt.hex
      - --suggested-fee-recipient=0x764a3D06E365e73085Bb489Da970E438F3C01c75
      - --checkpoint-sync-url=https://beaconstate.ethstaker.cc,https://sync-mainnet.beaconcha.in,https://mainnet-checkpoint-sync.stakely.io
      - --weak-subjectivity-checkpoint=14700000:0x3d6d6d6a9b4e9c8d0d3e6e2e3e8d3a0e6b2e3d6c6e8e3d6e2e3d6e8e3d6e2e3d6
      - --datadir=/data
      - --grpc-gateway-host=0.0.0.0
      - --grpc-gateway-port=3500
      - --monitoring-host=0.0.0.0
      - --monitoring-port=8080
      - --p2p-host-ip=0.0.0.0
      - --p2p-tcp-port=13000
      - --p2p-udp-port=12000
      - --bolt-mmap-initial-size=1073741824
      - --slashing-protection-history-export-dir=/data/slashing-protection
      - --enable-validator-monitoring
      - --enable-historical-state
      - --execution-timeout=120s
      - --jwt-id=Geth-Prysm