name: Deploy Ethereum Stack

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [main]
    paths:
      - 'deploy.sh'   # Only run when deployment logic changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate JWT Secret (if missing)
        id: jwt
        run: |
          if [ ! -f jwt.hex ]; then
            openssl rand -hex 32 > jwt.hex
            echo "Generated new JWT secret"
          else
            echo "Using existing JWT secret"
          fi
          echo "::add-mask::$(cat jwt.hex)"  # Hide in logs

      - name: Start Minikube
        run: |
          minikube start --driver=docker --memory=8g --cpus=4
          minikube ssh "sudo mkdir -p /mnt/{geth-data,prysm-data} && sudo chmod 777 /mnt/{geth-data,prysm-data}"

      - name: Deploy
        run: |
          kubectl create secret generic jwt-secret --from-file=jwt.hex=jwt.hex
          kubectl apply -f geth-prysm-deployment.yaml
          kubectl wait --for=condition=Ready pod -l app=geth --timeout=300s

      - name: Verify
        run: |
          kubectl get pods
          echo "Geth logs:"
          kubectl logs -l app=geth --tail=20